obj-m    += oplus_link_power.o

oplus_link_power-objs := linkpower_main.o
oplus_link_power-objs += linkpower_netlink/linkpower_netlink.o
oplus_link_power-objs += sk_pid_hook/sk_pid_hook.o
oplus_link_power-objs += data_wakeup_hook/data_wakeup_hook.o
