
obj-m += oplus_snshub.o
oplus_snshub-objs += snshub.o


obj-m += oplus_comm_master.o
oplus_comm_master-objs += comm_master.o


obj-m += oplus_comm_master_bt.o
oplus_comm_master_bt-objs += hci_bcsp_hook.o comm_master_plus.o
